version: "3.5"
services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: graphit-app/server:latest
    ports:
      - "8081:8081"
